CREATE TABLE users (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  first_name    VARCHAR2(100) NOT NULL,
  last_name    VARCHAR2(100),
  email         VARCHAR2(200) NOT NULL,
  password_hash VARCHAR2(200) NOT NULL,
  created_at    DATE DEFAULT SYSDATE,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE roles (
  id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR2(50) NOT NULL,
  CONSTRAINT pk_roles PRIMARY KEY (id),
  CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE TABLE user_roles (
  user_id NUMBER NOT NULL,
  role_id NUMBER NOT NULL,
  CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles(id)
);
