create table users (
   id            number generated by default as identity,
   first_name    varchar2(100) not null,
   last_name     varchar2(100),
   email         varchar2(200) not null,
   password_hash varchar2(200) not null,
   created_at    date default sysdate,
   constraint pk_users primary key ( id ),
   constraint uk_users_email unique ( email )
);

create table roles (
   id   number generated by default as identity,
   name varchar2(50) not null,
   constraint pk_roles primary key ( id ),
   constraint uk_roles_name unique ( name )
);

create table user_roles (
   user_id number not null,
   role_id number not null,
   constraint pk_user_roles primary key ( user_id,
                                          role_id ),
   constraint fk_ur_user foreign key ( user_id )
      references users ( id ),
   constraint fk_ur_role foreign key ( role_id )
      references roles ( id )
);